packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
    '@biomejs/biome': ^1.9.4

    '@t3-oss/env-core': ^0.13.6
    '@t3-oss/env-nextjs': ^0.13.6

    '@dotenvx/dotenvx': ^1.44.2
    jiti: ^2.4.2

    tailwindcss: ^3.4.17

    typescript: ~5.8.3
    zod: ^3.25.56

catalogs:
    react19:
        react: ~19.0.0
        react-dom: ~19.0.0
        '@types/react': ~19.0.0
        '@types/react-dom': ~19.0.0
    node22:
        '@types/node': ^22.11

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
  - sharp

patchedDependencies:
    better-auth: patches/better-auth.patch
